services:
  backend:
    image: tfg-backend:prod
    build:
      context: ./backend
      target: prod
    container_name: cluedo_backend_prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"

  frontend:
    image: tfg-frontend:prod
    build:
      context: ./frontend
      target: prod
      args:
        VITE_API_URL: /api
    container_name: cluedo_frontend_prod
    depends_on:
      - backend
    ports:
      - "8080:80"